server:
  port: 9001

spring:
  application:
    name: springcloud-alibaba-nacos-provider
  cloud:
    nacos:
      discovery:
       # server-addr: localhost:8848      # nacos 注册地址 注意没有 http://
        server-addr: 192.168.217.128:9090     # 注册到 linux 中nacos 集群中 （三个nacos服务 一个nginx服务） 此处填写的是 nginx 的地址和端口

management:
  endpoints:
    web:
      exposure:
        include: '*'