server:
  port: 9002

spring:
  application:
    name: springcloud-alibaba-nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848      # nacos 注册地址 注意没有 http://

management:
  endpoints:
    web:
      exposure:
        include: '*'