server:
  port: 8008


spring:
  application:
    name: springcloud-stream-consumer
  cloud:
    stream:
      binders:                                #在此处配置要绑定的rabbitmq的服务信息;
        defaultRabbit:                        #表示定义的名称，用于了binding整合
          type: rabbit                        #消息组件类型
          environment:                        #设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: ericjaylsh.xyz
                port: 5672
                username: guest
                password: guest
      bindings:                               #服务的整合处理
        input:                               #这个名字是一个通道的名称
          destination: firstExchange          #表示要使用的Exchange名称定义
          content-type: application/json      #设置消息类型，本次为json，文本则设置"text/plain”
          binder: defaultRabbit               #设置要绑定的消息服务的具体设置
          group: G1                           #添加分组（1.为了解决同类型消费者对消息重复消费，设置为相同分组即可，其对同一消息存在竞争关系 2.解决消息持久化问题当消费者停机后生产者发送了消息，重启消费者之后依旧可以得到消息）
    loadbalancer:
      ribbon:
        enabled: false
# spring.cloud.loadbalancer.ribbon.enabled` to `false`



#####################################
eureka:
  client:
    service-url:
      defaultZone: http://ericjaylsh.dev.xyz:7001/eureka/
    #      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
    #表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
  instance:
    # 修改主机名
    instance-id: springcloud-stream-consumer
    # 注册IP(访问可现实IP)
    prefer-ip-address: true
