spring:
  profiles:
    active: info


# 自定义配置
nacos:
  provider-server:
    name: http://springcloud-alibaba-nacos-provider




#####################################################################################
#####################################################################################

#nacos 持久化和集群配置

#nacos 安装目录下找到文件：F:\work\2020\nacos-server-1.1.4\nacos\conf\nacos-mysql.sql


#  1.安装数据库，版本要求：5.6.5+
#  2.初始化mysql数据库，数据库初始化文件：nacos-mysql.sql
#  3.修改conf/application.properties文件，增加支持mysql数据源配置（目前只支持mysql），添加mysql数据源的url、用户名和密码。

#  spring.datasource.platform=mysql

#  db.num=1
#  db.url.0=jdbc:mysql://11.162.196.16:3306/nacos_devtest?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true
#  db.user=nacos_devtest
#  db.password=youdontknow

#重启nacos