server:
  port: 4001

spring:
  application:
    name: springcloud-alibaba-nacos-sentinel-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848      # nacos 注册地址 注意没有 http://
        # server-addr: 192.168.217.128:9090     # 注册到 linux 中nacos 集群中 （三个nacos服务 一个nginx服务） 此处填写的是 nginx 的地址和端口
    sentinel:
      transport:
        port: 8719                # sentinel 展示端口 自增
        dashboard: localhost:9033 # sentinel 地址
      # 设置sentinel 流控规则的保存位置
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-tyoe: json
            rule-type: flow


management:
  endpoints:
    web:
      exposure:
        include: '*'


# 开启openfeign 对sentinel 的支持
feign:
  sentinel:
    enabled: true